application: nopullrequests
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/home.html
  upload: static/home.html

- url: /.*
  script: _go_app
